version: '3.8'

volumes:
  postgres-data:
    driver: local

services:
  database:
    image: postgres:9.6
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BattleRoomDbPassword
        
  battle-room-end2end-test:
    build:
      context: .
      dockerfile: ./Tests/BattleRoom.Tests.End2End.Launcher/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - BattleRoomApiUrl=http://host.docker.internal:5000
      - LobbiesHubUrl=http://host.docker.internal:5000/lobbies
    restart: always