version: '3.8'

volumes:
  postgres-data:
    driver: local
  

services:
  database:
    image: postgres:9.6
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5050:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BattleRoomDbPassword

  battle-room-api:
    build:
      context: .
      dockerfile: ./BattleRoom.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnection__Host=database
      - DbConnection__Port=5432
      - DbConnection__Username=postgres
      - DbConnection__Password=BattleRoomDbPassword
      - DbConnection__Database=BattleRoom.Db
    restart: always
    ports:
      - 5056:80
    depends_on:
      - database